config/routes.rb
Communirb::Application.routes.draw do
  root "home#index"
  
  get 'my-account' => 'user#account', as: 'user_account'
  patch 'my-account' => 'user#account_save'
  
  get 'my-profile' => 'user#profile', as: 'user_profile'
  patch 'my-profile' => 'user#profile_save'
  
  get 'search' => 'user#search', as: 'user_search'
  
  devise_for :users
  
  get 'users/:user_name' => 'user#lookout'

  get 'search/users/:text' => 'user#users_search'
  
end

app/models/message.rb
class Message < ActiveRecord::Base
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:login]

    has_many :messages
    
    attr_accessor :login

    serialize :friends
    validates :user_name, uniqueness: { case_sensitive: false }
         
    def self.find_first_by_auth_conditions(warden_conditions)
      conditions = warden_conditions.dup
      if login = conditions.delete(:login)
        where(conditions).where(["lower(user_name) = :value OR lower(email) = :value", { :value => login.downcase }]).first
      else
        where(conditions).first
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :user_name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:user_name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
        @messages = Message.where destination_id: current_user.id
        render 'user/dashboard'
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action :authenticate_user!
    before_filter :set_user, only: [:profile, :account]

    def account; end

    def profile; end

    def profile_save
        current_user.update_attributes!(user_params)
        redirect_to action: :profile
    end

    def account_save
        current_user.update_attributes!(user_params)
        redirect_to action: :account
    end

    def search
        @angularAppName = 'Search'
        @users = User.where.not(id: current_user.id)
    end

    def users_search
        q = "%#{params[:text]}%"
        result = User.where("name like ? or location like ? and id != ?", q, q, current_user.id)
        puts result.count
        render json: result
    end

    def lookout
        @user = User.find_by(user_name: params[:user_name])
        @messages = Message.where destination_id: @user.id
    end

    private

    def set_user
        @user = current_user
    end
    
    def user_params
        params.require(:user).permit(:name, :age, :bio, :gender, :location, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/index.html.erb
<p>Welcome to Communirb, a sample web to show a possible way to use Ruby on Rails to build a Social Network. If you want to try it out, just log in or register a new user and play around.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html <%= 'ng-app=' + @angularAppName if @angularAppName %>>
<head>
    <title>Communirb</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
</head>
<body>
    <div class="col-lg-offset-1 col-lg-10" id="container">
        <header>
            <h1><%= link_to 'Communirb - Social Network', root_path %></h1>
        </header>
        <nav class="col-lg-offset-7">
            <% if user_signed_in? %>
                <%= link_to 'Search people', user_search_path %> | 
                <%= link_to 'Dashboard', root_path %> | 
                <%= link_to 'My account', user_account_path %> | 
                <%= link_to 'My profile', user_profile_path %> | 
                <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
            <% else %>
                <%= link_to 'Register', new_user_registration_path %> | 
                <%= link_to 'Log in', new_user_session_path %>
            <% end %>
        </nav>
        <%= yield %>
    </div>
    <footer class="col-lg-offset-1 col-lg-10">
        <p>See the repo of this site at <%= link_to 'Github', 'https://github.com/igncp' %>.</p>
    </footer>
</body>
</html>

app/views/user/account.html.erb
<h1>My account</h1>

<p>Account: <strong><%= @user.user_name %></strong> (You can't change this)</p>

<%= form_for(@user, url: user_account_path) do |f| %>
    <p>Email: <%= f.text_field :email %></p>
    <p><%= f.submit 'Save' %></p>
<% end %>

app/views/user/dashboard.html.erb
<h1>Dashboard</h1>

<% @messages.each do |message| %>
    <p><a href="/users/<%= message.user.user_name %>"><%= message.user.name %></a> said: <%= message.content %></p>
<% end %>

app/views/user/lookout.html.erb
<h1>Lookout of <%= @user.name %></h1>

<p>Age: <%= @user.age %></p>
<p>Location: <%= @user.location %></p>
<p>Gender: <%= @user.gender %></p>
<p>Bio: <%= @user.bio %></p>

<% if @messages and @messages.count > 0 %>
    <p>--</p>
    <% @messages.each do |message| %>
        <p><a href="/users/<%= message.user.user_name %>"><%= message.user.name %></a> said: <%= message.content %></p>
    <% end %>
<% end %>

app/views/user/profile.html.erb
<h1>My profile</h1>

<%= form_for(@user, url: user_profile_path) do |f| %>
    <p>Name: <%= f.text_field :name %></p>
    <p>Age: <%= f.select :age, (0..101).to_a %></p>
    <p>Bio: <%= f.text_area :bio %></p>
    <p>Gender: <%= f.select :gender, [['Male', 'M'], ['Female', 'F']] %></p>
    <p>Location: <%= f.text_field :location %></p>
    <p><%= f.submit 'Save' %></p>
<% end %>

app/views/user/search.html.erb
<%= javascript_include_tag "user/search.js" %>

<h1>Search</h1>
<p>The users will be searched by uname or by location</p>
<div ng-controller="AppCtrl">
    
    <div>
        <input ng-model="query" type="text">
        <button id="search" ng-click="search()">Search</button>
    </div>
    
    <div ng-show="users.length == 0"> <p>No results for this text.</p> </div>
    <div ng-repeat="u in users" class="search-user-result">
        <p><a href="/users/{{u.user_name}}">{{u.name}}</a></p>
        <p>Age: {{u.age}}</p>
        <p>Location: {{u.location}}</p>
        <p>email: {{u.email}}</p>
    </div>
</div>

<%= javascript_tag do %>
  window.app = {}
  window.app.user_id = <%= current_user.id %>
<% end %>